### ISSUE TITLE
composer 安装ueditor报错

### ISSUE THREAD

**Issue by jimmylin66** [jqhph/dcat-admin-ueditor#7]
- Laravel Version: 7.29.2
- PHP Version: 7.4.5
- Dcat Admin Version: v2.0.6-beta
composer 安装ueditor报错：
composer require dcat-admin-extension/ueditor
1/1:	https://mirrors.aliyun.com/composer/p/provider-latest$ab69e16a7da18f74f2879f424b96565b70f60cb11596d4514ce27d1dc2a39964.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Using version dev-master for dcat-admin-extension/ueditor
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Fatal error:  Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php:4
Stack trace:
#0 /home/vagrant/code/cms/vendor/composer/autoload_real.php(69): require()
#1 /home/vagrant/code/cms/vendor/composer/autoload_real.php(59): composerRequire2777f953bda6b748e883e3991ec109ce()
#2 /home/vagrant/code/cms/vendor/autoload.php(7): ComposerAutoloaderInit2777f953bda6b748e883e3991ec109ce::getLoader()
#3 /home/vagrant/code/cms/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/home/vagrant/c...')
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Illuminate\Foundation\ComposerScripts::postAutoloadDump()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#6 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\E in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php on line 4

Fatal error: Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php:4
Stack trace:
#0 /home/vagrant/code/cms/vendor/composer/autoload_real.php(69): require()
#1 /home/vagrant/code/cms/vendor/composer/autoload_real.php(59): composerRequire2777f953bda6b748e883e3991ec109ce()
#2 /home/vagrant/code/cms/vendor/autoload.php(7): ComposerAutoloaderInit2777f953bda6b748e883e3991ec109ce::getLoader()
#3 /home/vagrant/code/cms/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/home/vagrant/c...')
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Illuminate\Foundation\ComposerScripts::postAutoloadDump()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#6 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\E in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php on line 4
vagrant@homestead:~/code/cms$ php artisan admin:import ueditor
PHP Fatal error:  Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php:4
Stack trace:
#0 /home/vagrant/code/cms/vendor/composer/autoload_real.php(69): require()
#1 /home/vagrant/code/cms/vendor/composer/autoload_real.php(59): composerRequire2777f953bda6b748e883e3991ec109ce()
#2 /home/vagrant/code/cms/vendor/autoload.php(7): ComposerAutoloaderInit2777f953bda6b748e883e3991ec109ce::getLoader()
#3 /home/vagrant/code/cms/artisan(18): require('/home/vagrant/c...')
#4 {main}
  thrown in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php on line 4

Fatal error: Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php:4
Stack trace:
#0 /home/vagrant/code/cms/vendor/composer/autoload_real.php(69): require()
#1 /home/vagrant/code/cms/vendor/composer/autoload_real.php(59): composerRequire2777f953bda6b748e883e3991ec109ce()
#2 /home/vagrant/code/cms/vendor/autoload.php(7): ComposerAutoloaderInit2777f953bda6b748e883e3991ec109ce::getLoader()
#3 /home/vagrant/code/cms/artisan(18): require('/home/vagrant/c...')
#4 {main}
  thrown in /home/vagrant/code/cms/vendor/dcat-admin-extension/ueditor/src/bootstrap.php on line 4

**Comment by leeyisoft** [comment]
遇到同样的问题，求解答

**Comment by jimmylin66** [comment]
@leeyisoft 我最后用了文档上的wangeditor 
http://www.dcatadmin.com/docs/2.x/model-form-field-management.html#%E9%9B%86%E6%88%90%E5%AF%8C%E6%96%87%E6%9C%AC%E7%BC%96%E8%BE%91%E5%99%A8wangEditor-h3

**Comment by mrjie123** [comment]
遇到同样的问题，求解答

**Comment by GiveUpPHP** [comment]
这个扩展是不是只适用于dcat 1.x，我的2.0没法用呢

**Comment by lyne007** [comment]
遇到同样的问题，求解答
